const database = {
    fish: [
        {
            id: 1,  
            image: `./images/sparkle-gourami`,
            fishName: `Sparkle Gourami`,
            species: `Trichopsis pumila`,
            length: 2,
            harvestLocation: `Southeast Asia`,
            diet: `small insects`,
        },
        {
            id: 2,  
            image: `./images/electric-blue-acara.webp`,
            fishName: `Electric Blue Acara`,
            species: `Andinoacara pulcher`,
            length: 6,
            harvestLocation: `South America`,
            diet: `small invertebrates`,
        },
        {
            id: 3,  
            image: `./images/redtail-catfish.webp`,
            fishName: `Redtail Catfish`,
            species: `Phractocephalus hemioliopterus`,
            length: 5,
            harvestLocation: `South America`,
            diet: `small fish and insects`,
        },
        {
            id: 4,  
            image: `./images/rainbowfish.webp`,
            fishName: `Rainbowfish`,
            species: `Melanotaenia spp.`,
            length: 4,
            harvestLocation: `Australia`,
            diet: `bloodworms and algae`,
        },
        {
            id: 5,  
            image: `./images/discus.webp`,
            fishName: `Discus`,
            species: `Symphysodon spp.`,
            length: 8,
            harvestLocation: `South America`,
            diet: `bloodworms and brine shrimp`,
        },
        {
            id: 6,  
            image: `./images/bristlenose-pleco.webp`,
            fishName: `Bristlenose Pleco`,
            species: `Ancistrus spp.`,
            length: 5,
            harvestLocation: `South America`,
            diet: `algae and biofilm`,
        },
        {
            id: 7,  
            image: `./images/archerfish.webp`,
            fishName: `Archerfish`,
            species: `Toxotes spp.`,
            length: 11,
            harvestLocation: `Southeast Asia`,
            diet: `small fish and insects`,
        },
        {
            id: 8,  
            image: `./images/clown-loach.webp`,
            fishName: `Clown Loach`,
            species: `Chromobotia macracanthus`,
            length: 6,
            harvestLocation: `Indonesia`,
            diet: `bloodworms and brine shrimp`,
        },
        {
            id: 9,  
            image: `./images/neon-tetra.webp`,
            fishName: `Neon Tetra`,
            species: `Paracheirodon innesi`,
            length: 1.5,
            harvestLocation: `Amazon Basin`,
            diet: `bloodworms and brine shrimp`,
        },
        {
            id: 10,  
            image: `./images/corydoras-catfish.webp`,
            fishName: `Corydoras Catfish`,
            species: `Corydoras spp.`,
            length: 3,
            harvestLocation: `South America`,
            diet: `bloodworms and alae`,
        },
        {
            id: 11,  
            image: `./images/dwarf-gourami.webp`,
            fishName: `Dwarf Gourami`,
            species: `Trichogaster lalius`,
            length: 2,
            harvestLocation: `Southeast Asia`,
            diet: `brine shrimp and algae`,
        },
        {
            id: 12,  
            image: `./images/siamese-fighting-fish.webp`,
            fishName: `Siamese Fighting Fish`,
            species: `Betta splendens`,
            length: 3,
            harvestLocation: `Southeast Asia`,
            diet: `small insects`,
        },
        {
            id: 13,  
            image: `./images/tiger-barb.webp`,
            fishName: `Tiger Barb`,
            species: `Puntigrus tetrazona`,
            length: 2.5,
            harvestLocation: `Southeast Asia`,
            diet: `bloodworms and brine shrimp`,
        },
        {
            id: 14,  
            image: `./images/angelfish.webp`,
            fishName: `Angelfish`,
            species: `Pterophyllum scalare`,
            length: 6,
            harvestLocation: `South America`,
            diet: `small crustaceans`,
        },
        {
            id: 15,  
            image: `./images/zebra-danio.webp`,
            fishName: `Zebra Danio`,
            species: `Danio rerio`,
            length: 2,
            harvestLocation: `india`,
            diet: `brine shrimp and algae`,
        }
    ]
}